name: Ejecutar an치lisis Estadistico JMeter

on:
  workflow_dispatch:
    inputs:
      ruta_escenarios:
        description: 'Ruta de la carpeta que contiene los EscenarioN'
        required: true
        default: 'D:\BackupX13\D_LUIS_lOPEZ\CMD_Jmeter\GPO'

jobs:
  run-analysis:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Habilitar ejecuci칩n de scripts
        run: powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force"

      - name: Ejecutar an치lisis
        run: python D:\jmeter_regresion_analysis\main.py

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas matplotlib scipy reportlab

      - name: Ejecutar script de an치lisis
        run: |
          python scripts/jmeter_regresion_analysis.py "${{ github.event.inputs.ruta_escenarios }}"